-- AlterTable
ALTER TABLE "public"."Cashier" ADD COLUMN     "dailyNumber" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN     "isClaimed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "jackpotEnabled" TEXT NOT NULL DEFAULT 'Off',
ADD COLUMN     "jackpotPercent" DOUBLE PRECISION NOT NULL DEFAULT 25,
ADD COLUMN     "jackpotStartingAmount" DOUBLE PRECISION NOT NULL DEFAULT 200,
ADD COLUMN     "matchGap" INTEGER NOT NULL DEFAULT 5;
